### ISSUE TITLE
[Question] Example to play with it

### ISSUE THREAD

**Issue by rcrespocano** [baccuslab/deep-retina#10]
Hello,

Is there an example to be able to use your neural network with natural images? For example, by using some images or video files as the input. I'm thinking in a way to use your fantastic tool in the same manner that the Virtual-Retina framework (https://link.springer.com/article/10.1007/s10827-008-0108-4). I guess you know what I'm talking about :)

Thank you so much in advance.

Kind regards,
Rubén

**Comment by nirum** [comment]
Hi Rubén,

Thanks for your interest! We are planning on releasing an update with a pre-trained model that you can use to simulate retinal responses sometime in the fall. We will notify you once we do.

thanks,
Niru

**Comment by rcrespocano** [comment]
Thanks!
Rubén
