### ISSUE TITLE
m = convnet() fails at super()

### ISSUE THREAD

**Issue by lmcintosh** [baccuslab/deep-retina#2]
![image](https://cloud.githubusercontent.com/assets/543568/10983400/28c6e7ce-83c7-11e5-863d-98856387bb51.png)

Apparently super() needs at least one argument. I tried just using "self" but it "needs a type, not convnet".

**Comment by nirum** [comment]
this is a python2/3 thing

I'll fix it be backwards compatible :back:

**Comment by nirum** [comment]
I believe 8f88c1ca9e079f93d488502631c6c25fb0fcb00c fixes this

**Comment by lmcintosh** [comment]
gracias!


--
Lane McIntosh
www.lanemcintosh.com
