### ISSUE TITLE
can you provide some images dataset and pre-trained model?

### ISSUE THREAD

**Issue by IvyGongoogle** [baccuslab/deep-retina#9]
hello, like your repository. But can you provide some images dataset and pre-trained models?

thank you very much~

**Comment by lmcintosh** [comment]
Thanks for your interest in the repository! The natural images we used in our natural scenes movies are publicly available here: http://tofu.psych.upenn.edu/~upennidb/. We hope to release some pre-trained models soon!

**Comment by IvyGongoogle** [comment]
@lmcintosh thank you very much!
